name: Test python app
on: 
  push:
    branches: [dev]
jobs:
  Run-Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r /Lambda/lambda_function/requirements.txt
      - name: Run tests with pytest
        run: pytest 