name: Deploy Lambda
on: 
  push:
    branches: [main]
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Zip code
        run: |
          cd Lambda && ls && zip deployment.zip lambda_function/
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
          function_name: budget_scheduler
          zip_file: Lambda/deployment.zip
          memory_size: 128
          timeout: 35
          handler: lambda_function.lambda_handler
          role: arn:aws:iam::982658172500:role/lambda_budget_scheduler_policy
          runtime: python3.7 
